// Home Language File - English - r2018-06-06 fr2018-02-05
// Copy this file and rename it as lang_current.js

var es_dwds=new Array('Mon','Tue','Wed','Thu','Fri','Sat','Sun'); // Names of the days of the week
var es_dwds2=new Array('Mo','Tu','We','Th','Fr','Sa','Su'); // Names of the days of the week (shorter)
var es_dmms=new Array('Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'); // Names of the months
var es_zs=new Array('Aries','Taurus','Gemini','Cancer','Leo','Virgo','Libra','Scorpio','Sagittarius','Capricorn','Aquarius','Pisces'); // Zodiacal Signs
var es_zsc=new Array('Shu (Mouse)', 'Niu (Ox)', 'Hu (Tiger)', 'Tu (Rabbit)', 'Long (Dragon)', 'She (Snake)', 'Ma (Horse)', 'Xang (Goat)', 'Hou (Monkey)', 'Ji (Rooster)', 'Gou (Dog)', 'Zhu (Pig)'); // Chinese Zodiac

var es_y='Yes';
var es_n='No';
var es_cal='Calendar';
// var es_dd='Day';
var es_dds='Days';
// var es_mm='Month';
// var es_mms='Months';
var es_yy='Year';
// var es_yys='Years';
var es_today='Today';
var es_tlocal='Local';
var es_tutc='UTC';
var es_yfondrome='Foundation of Rome';
var es_ygregref='Gregorian Reform';
var es_yjws='Jewish Year';
var es_ymsm='Muslim Year';
var es_ylp='Leap year';
var es_ylbbc='BC';
var es_ylbad='AD';
var es_ylbau='AUC';
var es_ylbam='AM';
var es_ylbah='H';
var es_easter='Easter';
var es_cnzd='Chinese Zodiac';
var es_passed='Passed';
var es_togo='To go';
var es_jd='Julian Day';
var es_mjd='Mod. Julian Day';
var es_ratd='Rata Day';
var es_zodsign='Zodiac Sign';
var es_yin='Yin';
var es_yang='Yang';
var es_earth='Earth';
var es_water='Water';
var es_fire='Fire';
var es_air='Air';
var es_metal='Metal';
var es_wood='Wood';
var es_scnres='Screen resolution';
var es_coldep='Color depth';
var es_colors='Colors';
var es_color='Color';
var es_colrgbh='RGB H';
var es_colrgbd='RGB D';
var es_colhsl='HSL';
var es_colhsv='HSV';
var es_colcmyk='CMYK';
var es_winsiz='Window size';
var es_chars='Characters';
var es_mapw='World Map';
var es_favs='Favorites';
var es_theme='Theme';
var es_thmnone='None';
var es_thmauto='Auto';
var es_thmlite='Light';
var es_thmdark='Dark';
var es_enab='Enabled';
// var es_disb='Disabled';
var es_online='Online';
var es_offline='Offline';
var es_mousepos='Mouse';
// var es_x='X';
// var es_y='Y';
var es_calc='Calc';
var es_entplc='Enter a Place or a Coordinate';
var es_mypos='My Position';
var es_posno='Sorry, I can\'t get your coordinates.';
var es_poschkperm='Check the Privacy settings in your browser and system.';
var es_go='Go';
var es_pageloaded='Page Loaded';
var es_thequickfox='The quick brown Fox jumps over the lazy Dog';
var es_about='About';
